# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Production Environment Infrastructure Configuration
# --- USER ACTION REQUIRED: Update values below ---
variables:

  # --- Global Settings ---
  # Define a short, lowercase alphanumeric namespace for your project (e.g., 'fraudproj')
  # Note: Max length constraints apply to derived names (e.g., storage accounts max 24 chars). Keep it short.
  namespace: fraudtrml # EXAMPLE: Replace with your project namespace
  # Define a short, unique postfix (e.g., initials, random chars like 'a0b1')
  postfix: fdx012 # EXAMPLE: Replace with your unique postfix
  # Azure region for deployment (e.g., 'westus2', 'eastus', 'westeurope')
  location: westeurope # EXAMPLE: Replace with your desired Azure region

  # Environment identifier (used in resource naming)
  environment: prod

  # --- Feature Flags ---
  # Enable creation of a default CPU compute cluster in AML Workspace?
  enable_aml_computecluster: true
  # Enable creation of Azure Data Explorer for monitoring (adds cost)?
  enable_monitoring: false
  # Enable secure workspace features (e.g., VNet integration - requires more setup)?
  enable_aml_secure_workspace: false # Set to true for VNet scenarios


  # Azure DevOps
  # ado_service_connection_rg: Azure-ARM-Prod
  # ado_service_connection_aml_ws: Azure-ARM-Prod

  # DO NOT TOUCH

  # For pipeline reference
  resource_group: rg-$(namespace)-$(postfix)$(environment)
  aml_workspace: mlw-$(namespace)-$(postfix)$(environment)
  application_insights: mlw-$(namespace)-$(postfix)$(environment)
  key_vault: kv-$(namespace)-$(postfix)$(environment)
  container_registry: cr$(namespace)$(postfix)$(environment)
  storage_account: st$(namespace)$(postfix)$(environment)

  # For terraform reference
  terraform_version: 0.14.7
  terraform_workingdir: infrastructure
  terraform_st_resource_group: rg-$(namespace)-$(postfix)$(environment)-tf
  terraform_st_location: $(location)
  terraform_st_storage_account: st$(namespace)$(postfix)$(environment)tf
  terraform_st_container_name: default
  # terraform_st_container_name: tfstate
  terraform_st_key: mlops-tab
  # terraform_st_key: fraud-mlops-$(environment).tfstate


  # Batch/Online Endpoint names (example derivation, adjust as needed)
  # Ensure these result in valid Azure resource names
  bep: fraud-batch-ep-$(postfix) # Batch Endpoint name part
  oep: fraud-online-ep-$(postfix) # Online Endpoint name part