# Configuration for Production Infrastructure Deployment
# Used by Terraform workflows (.github/workflows/tf-gha-deploy-infra.yml)
# and potentially other workflows to get resource names.

variables:
  # --- Global Settings ---
  namespace: fraudmlops   # Choose a short, descriptive namespace (alphanumeric)
  postfix: f detección   # Unique identifier (e.g., generated string, date, sequence)
  location: westus2      # Azure region for deployment
  environment: prod      # Environment identifier ('dev', 'staging', 'prod')

  # --- Feature Flags ---
  enable_aml_computecluster: true # Create a default CPU compute cluster in AML?
  # enable_aml_secure_workspace: false # Enable network isolation features? (More complex setup)
  enable_monitoring: false        # Deploy Azure Data Explorer for monitoring?
  enable_acr: true                # Deploy Azure Container Registry? (Recommended)

  # --- Azure Resource Naming (Derived - DO NOT TOUCH unless structure changes) ---
  # These are derived from global settings above and used by workflows/scripts.
  resource_group: rg-$(namespace)-$(postfix)$(environment)
  aml_workspace: mlw-$(namespace)-$(postfix)$(environment)
  application_insights: appi-$(namespace)-$(postfix)$(environment) # Matches module naming
  key_vault: kv-$(namespace)-$(postfix)$(environment)      # Matches module naming
  # ACR naming needs sanitization (lowercase, no hyphens) - This reflects the expected *output* name
  # Terraform module handles the sanitization logic. Example output: crfraudmlopsfdetectionprod
  container_registry_tf_safe: cr$(namespace)$(postfix)$(environment)
  # Storage account naming needs sanitization - Example output: stfraudmlopsfdetectionprod
  storage_account_tf_safe: st$(namespace)$(postfix)$(environment)

  # --- Endpoint Names ---
  # These names will be used for deploying models via GitHub Actions workflows.
  oep: fraud-detection-online  # Online Endpoint name
  bep: fraud-detection-batch   # Batch Endpoint name

  # --- Terraform Specific Settings ---
  terraform_version: 1.1.7 # Specify Terraform version to use in workflow (adjust as needed)
  terraform_workingdir: infrastructure # Directory containing root Terraform configuration

  # --- Terraform Backend Configuration ---
  # Details for the Azure Storage Account used to store Terraform state.
  # IMPORTANT: This storage account/container MUST exist before running the infra workflow.
  # Consider creating it manually or via a separate bootstrap script/template.
  terraform_st_resource_group: rg-tfstate-mgmt # Example: RG name for Terraform state storage
  terraform_st_location: $(location)         # Location for state storage (can be different from main deployment)
  terraform_st_storage_account: stfraudmlopstfstate # Example: Storage account name for TF state
  terraform_st_container_name: tfstate            # Container name within the storage account
  terraform_st_key: fraud-detection-$(environment).tfstate # State file name (specific to environment)