name: custom-notebook-env-conda-adapted
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - python-graphviz=0.19.1  
  - imbalanced-learn=0.8.1
  - matplotlib             
  - numpy=1.19.5
  - pandas=1.3.5
  - pandarallel=1.5.4
  - scikit-learn=1.0.0
  - seaborn=0.11.2
  - Sphinx=4.2.0
  - sphinxcontrib-bibtex=2.2.1
  - xgboost=1.5.1
  - pip:
      - dvc[azure]  
      - mlflow      
      - azureml-sdk 
      - azureml-mlflow
      - azure-identity
