# File: mlops/azureml/deploy/online/online-deployment.yml

$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: blue # Or your deployment name
endpoint_name: fraud-detection-online # Must match the name in online-endpoint.yml
description: Blue deployment for the real-time fraud detection model.
model: azureml:fraud-detection-model@latest # Reference the registered model
instance_type: Standard_DS2a_v4 # Or your desired instance type
instance_count: 1

# --- Add/Modify Code and Environment ---
# Ensure you specify the code containing score.py and the environment with dependencies
code_configuration:
  code: ../../../data-science/src # Points to the directory containing score.py and utils.py
  scoring_script: score.py
environment: azureml:fraud-detection-train-env@latest # Use the env with azureml-ai-monitoring

# --- Add Data Collector Configuration ---
data_collector:
  # rolling_rate removed - Default partitioning based on ingestion time will be used.
  # The default storage path structure still provides YYYY/MM/DD/HH granularity.
  collections:
    # Enable the collector named 'model_inputs' in score.py
    model_inputs:
      enabled: 'True'
      # Optional: Define specific data asset details if you don't want the default
      # data:
      #   name: my_model_inputs_asset_name # Custom asset name
      #   path: azureml://datastores/workspaceblobstore/paths/my_custom_path/inputs # Custom path
      #   version: 1
    # Enable the collector named 'model_outputs' in score.py
    model_outputs:
      enabled: 'True'
      # Optional: Define specific data asset details
      # data:
      #   name: my_model_outputs_asset_name
      #   path: azureml://datastores/workspaceblobstore/paths/my_custom_path/outputs
      #   version: 1

# Optional: request_settings, probes etc. can remain as they were
# request_settings:
#   request_timeout_ms: 5000
# liveness_probe:
#   failure_threshold: 30
#   period_seconds: 10
# readiness_probe:
#   failure_threshold: 3
#   period_seconds: 10