# Conda environment specification for Fraud Detection Training Pipeline
# Based on user's environment.yml and MLOps requirements
name: fraud-detection-train-env
channels:
  - conda-forge # Prioritize conda-forge
  - defaults
dependencies:
  # --- Core Environment ---
  - python=3.9 # Align with user's notebook env
  - pip # IMPORTANT: Include pip itself

  # --- Data Handling & Core ML (from user's env) ---
  - numpy>=1.19.5,<1.24.0 # Example range, adjust if needed
  - pandas>=1.3.5,<1.6.0 # Example range, adjust if needed
  - scikit-learn>=1.0.0,<1.2.0 # Example range, adjust if needed
  - joblib # Often used with scikit-learn

  # --- Specific Libraries (from user's env) ---
  - imbalanced-learn>=0.8.1,<0.11.0 # Example range
  - xgboost>=1.5.1,<1.8.0 # Example range
  - matplotlib # Version compatibility handled by conda usually
  - seaborn>=0.11.2,<0.13.0 # Example range
  - python-graphviz>=0.19.1,<0.21.0 # Use 'python-graphviz' on conda
  - pandarallel>=1.5.4,<1.7.0 # Example range

  # --- MLOps & Azure ML ---
  - pip: # Use pip for Azure ML SDKs and MLflow
      - mlflow>=2.0,<2.10 # Keep mlflow updated
      # Choose V1 or V2 SDK based on preference/environment
      # - azureml-sdk>=1.50.0 # V1 SDK (as used in user notebooks)
      # - azureml-mlflow>=1.50.0 # V1 MLflow integration
      - azure-ai-ml>=1.5.0 # V2 SDK (Recommended for new development)
      - azure-identity>=1.10.0 # Often needed for V2 auth
      - msal>=1.20 # Dependency for azure-identity

      # DVC and Git (Optional, if used within pipeline steps)
      # - dvc[azure]>=2.0,<3.0
      # - GitPython>=3.1,<3.2

      # Cloudpickle often needed for pipeline serialization
      - cloudpickle>=2.0.0,<3.0.0

# Notes:
# - Version ranges are examples; adjust based on exact requirements and compatibility testing.
# - Consider pinning more versions for strict reproducibility.
# - Remove unused libraries (Sphinx?) if not needed for the pipeline steps.
# - If using V1 SDK (azureml-sdk), ensure compatibility with Python 3.9.
# - If using V2 SDK (azure-ai-ml), adjust imports and code in pipeline scripts accordingly.