# Conda environment specification for Fraud Detection Training Pipeline
# Based on user's environment.yml and MLOps requirements
name: fraud-detection-train-env
channels:
  - conda-forge 
dependencies:
  - python=3.9
  - pip

  
  - python-graphviz=0.19.1   
  - imbalanced-learn=0.8.1
  - matplotlib             
  - numpy=1.19.5
  - pandas=1.3.5
  - pandarallel=1.5.4
  - scikit-learn=1.0.0
  - seaborn=0.11.2
  - Sphinx=4.2.0
  - sphinxcontrib-bibtex=2.2.1
  - xgboost=1.5.1

  - pip:
      - dvc[azure]  
      - mlflow      
      - azureml-sdk 
      - azureml-mlflow
      - azure-ai-ml 
      - azure-identity # (often needed for authentication)
      - azureml-ai-monitoring
      - azureml-inference-server-http
      - mltable 
      - azureml-dataprep[pandas]
      - pyarrow
      - cloudpickle>=2.0.0,<3.0.0

# - If using V2 SDK (azure-ai-ml), adjust imports and code in pipeline scripts accordingly.